# Generated by Django 4.1.7 on 2026-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0007_alter_scorecard_computer_music_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
